#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

echo "-----------------------------------------------------"
echo "SETUP LARAVEL $(date)"
echo "-----------------------------------------------------"

cd /var/www/apps/backend

if [ ! -d "vendor" ]; then
    echo "Composer vendor folder was not installed. Running $> composer install --prefer-dist --no-interaction --optimize-autoloader --no-dev"
    composer install --prefer-dist --no-interaction --optimize-autoloader --no-dev
fi

#if [ "$OPTIMIZE" = true ]; then
#    echo "Laravel - Cache Optimization [Production]"
#    /usr/bin/php /var/www/html/apps/backend/artisan optimize
#fi

echo "-----------------------------------------------------"
echo "START SERVICES $(date)"
echo "-----------------------------------------------------"

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
